---
title: "Regime Previdenciário Atual dos Entes Federativos"
author: "Marcos F Silva"
date: "24/05/2021"
output: html_document
---

</br>

# Descrição da base

----

**Conteúdo:** 

Este arquivo contém a relação dos entes federativos e a indicação do regime previdenciário ao qual estão vinculados: Regime Geral de Previdência Social (RGPS) ou Regime Próprio de Previdência Social (RPPS).


</br>

**Fonte dos dados:** 

Dados disponibilizados pela Secretaria de Previdência Social do Ministério  da Economia (SPREV/ME) na página https://www.gov.br/previdencia/pt-br/assuntos/previdencia-no-servico-publico/estatisticas-e-informacoes-dos-rpps-1/estatisticas-e-informacoes-dos-rpps

</br>

**Problemas conhecidos na base:** 

* Não há consistência na nomeação dos arquivos das atualizações
* Os dados ora são disponibilizados em csv, ora em xlsx

</br>

**A implementar:**

* Importar diretamente do repositório do SERPRO

</br>

# Tratamento dos dados

----

## Carregamento dos pacotes necessários

```{r}
options(scipen = 999)
library(readr)
library(readxl)
library(dplyr)
```


## Importação dos dados


```{r}
regime_previdenciario_entes <- read_excel("../input/4-Regime Entes Federativos_Atualizacao_mar_2021_Extração_Em_2021-04-19T15_33_58.xlsx") %>%
                                          rename(cnpj_ente = CNPJ, 
                                          sigla_uf = UF,
                                          nome_ente = ENTE,
                                          regime = REGIME)  

head(regime_previdenciario_entes)
```


```{r}
# Quantidade de linhas e colunas:
dim(regime_previdenciario_entes)
```


</br>

# Exportar a base tratada

```{r}
write_csv2(regime_previdenciario_entes,
           path="../output/regime_previdenciario_entes.csv")
```


</br>

# Dicionário de dados

----

`cnpj_ente` : número do CNPJ do Ente Federativo    
`sigla_uf` : sigla da unidade da federação    
`nome_ente`: nome do Ente   
`regime`: regime previdenciário ao qual o Ente está vinculado

</br>





